# Generated by Django 4.1.3 on 2022-11-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armed_university',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя военного вуза')),
                ('location', models.CharField(max_length=120, verbose_name='Локация вуза')),
                ('descripton', models.TextField(verbose_name='Описание')),
                ('full_info', models.TextField(verbose_name='Полная информация')),
                ('country', models.CharField(max_length=120, verbose_name='Город')),
                ('main_img', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('img_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('img_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('img_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField()),
            ],
        ),
    ]
