# Generated by Django 4.1.3 on 2022-12-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armed_universities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armed_university',
            name='country',
        ),
        migrations.AlterField(
            model_name='armed_university',
            name='is_published',
            field=models.BooleanField(blank=True),
        ),
    ]
